const data = {
  1: [
    "Be patient and understanding.",
    "Ask for assistance from a supervisor if needed.",
    "Provide clear and detailed instructions.",
    "Maintain a polite and respectful attitude.",
    "Seek alternative options if necessary.",
    "Double-check any information or instructions provided.",
    "Share your concerns with the company's customer support.",
    "Consider providing feedback to help improve the service.",
    "Remain calm and composed.",
    "Give the employee an opportunity to rectify any mistakes.",
    "Ask for clarification if something is unclear.",
    "Report any issues to the appropriate authority.",
    "Focus on finding solutions rather than dwelling on the problem.",
    "Be open to giving the employee a second chance.",
    "Try to understand the challenges the employee might be facing.",
    "Express your dissatisfaction constructively.",
    "Keep a record of your interactions for future reference.",
    "Acknowledge that everyone can have an off day.",
    "Keep your expectations realistic.",
    "Consider sharing your experience with the company's management.",
  ],
  2: [
    "Provide specific feedback on areas that need improvement.",
    "Ask for a supervisor's assistance if necessary.",
    "Give the employee an opportunity to correct any mistakes.",
    "Express your concerns calmly and assertively.",
    "Suggest ways to enhance the service quality.",
    "Consider providing constructive suggestions for improvement.",
    "Seek clarification if something is unclear.",
    "Request a different employee if you feel more comfortable.",
    "Communicate your expectations clearly.",
    "Remain polite and courteous in your interactions.",
    "Be patient and understanding of the employee's efforts.",
    "Ask for a follow-up from the company to address your concerns.",
    "Offer a chance for the employee to explain their perspective.",
    "Consider providing feedback to help the employee learn and grow.",
    "Evaluate the overall service rather than focusing solely on the employee.",
    "Express your disappointment in a constructive manner.",
    "Remember that mistakes can happen, and people can learn from them.",
    "Be open to finding common ground and resolving any issues.",
    "Appreciate any efforts made by the employee to resolve the situation.",
    "Consider discussing your experience with the employee's supervisor.",
  ],
  3: [
    "Express your concerns in a respectful manner.",
    "Ask for a supervisor's assistance if necessary.",
    "Consider providing feedback on areas that could be improved.",
    "Be open to suggestions and alternatives provided by the employee.",
    "Give the employee a chance to address any issues or concerns.",
    "Request clarification if something is unclear.",
    "Offer constructive suggestions for improvement.",
    "Remain patient and give the employee time to resolve the situation.",
    "Acknowledge any effort made by the employee to rectify the problem.",
    "Communicate your expectations and needs clearly.",
    "Focus on finding a mutually beneficial solution.",
    "Keep a record of the interaction for future reference.",
    "Evaluate the overall service experience before forming a final opinion.",
    "Express your dissatisfaction with a focus on resolving the issue.",
    "Remember that employees can have off days but can still provide value.",
    "Appreciate any attempts by the employee to make amends.",
    "Consider discussing your experience with the company's management.",
    "Offer feedback to help the employee enhance their performance.",
    "Be respectful but assertive in expressing your concerns.",
    "Consider giving the employee a second chance to meet your expectations.",
  ],
  4: [
    "Acknowledge and appreciate the employee's efforts.",
    "Express your satisfaction with the service provided.",
    "Consider providing positive feedback to the employee.",
    "Share any exceptional experiences with the company's management.",
    "Highlight the employee's strengths and positive attributes.",
    "Offer constructive feedback for minor areas of improvement.",
    "Be courteous and respectful in your interactions.",
    "Express your gratitude for a job well done.",
    "Consider recommending the employee to others.",
    "Maintain open communication with the employee.",
    "Acknowledge and appreciate the employee's professionalism.",
    "Share any suggestions for enhancing the service experience.",
    "Recognize and value the employee's contributions.",
    "Offer positive feedback to help motivate the employee.",
    "Consider providing a testimonial or positive review.",
    "Express your satisfaction without being overly critical.",
    "Remember that employees thrive on recognition and encouragement.",
    "Appreciate the employee's responsiveness and attentiveness.",
    "Recognize and value the employee's knowledge and expertise.",
    "Consider providing feedback to the company to encourage similar experiences.",
  ],
  5: [
    "Express your utmost satisfaction with the service received.",
    "Appreciate the employee's exceptional performance.",
    "Share your positive experience with others.",
    "Highlight the employee's outstanding qualities to the management.",
    "Offer words of praise and commendation.",
    "Recognize the employee's dedication and commitment.",
    "Consider providing a glowing testimonial or review.",
    "Express your gratitude for the exceptional service provided.",
    "Remember that employees appreciate positive feedback and recognition.",
    "Acknowledge the employee's ability to exceed expectations.",
    "Share any suggestions for further enhancing the service experience.",
    "Celebrate the employee's professionalism and expertise.",
    "Maintain open communication and ongoing support for the employee.",
    "Consider recommending the employee for recognition or rewards.",
    "Express your satisfaction in a genuine and heartfelt manner.",
    "Recognize and value the employee's role in creating a positive experience.",
    "Offer words of encouragement and appreciation.",
    "Remember that employees thrive on positive reinforcement and encouragement.",
    "Appreciate the employee's attention to detail and proactive approach.",
    "Recognize and acknowledge the employee's exceptional customer service skills.",
    "Consider sharing your outstanding experience with the employee's superiors.",
    "Express your appreciation for the employee's going above and beyond.",
    "Share your positive encounter on social media or review platforms.",
    "Remember that employees play a crucial role in delivering excellent service.",
  ],
};

export default data;
